In [1]:
import numpy as np
import pandas as pd

In [2]:
#for 1000 words dataset
train = pd.read_csv("x_y_train.csv")
test = pd.read_csv("x_y_test.csv")

In [3]:
del train['Unnamed: 0']
del test['Unnamed: 0']

In [4]:
train.head()

subject  lines  date  path  organization  writes  references  article  \
0        1      1     1     1             1       0           0        0   
1        1      1     1     1             0       0           0        0   
2        1      2     1     1             1       1           1        1   
3        1      1     1     1             1       1           1        1   
4        1      1     1     1             1       1           1        1   

   sender  people       ...         modern  stay  countries  gm  heaven  \
0       1       0       ...              0     0          0   0       0   
1       1       0       ...              0     0          0   0       0   
2       1       0       ...              0     0          0   0       0   
3       0       0       ...              0     0          0   0       0   
4       0       0       ...              0     0          0   0       0   

   social  at&t  gateway  logic           _CLASS  
0       0     0        0      0  sci.electronics  
1       0     0        0      0  sci.electronics  
2       0     0        0      0  sci.electronics  
3       0     0        0      0  sci.electronics  
4       0     0        0      0  sci.electronics  

[5 rows x 1001 columns]

In [5]:
test.head()

subject  lines  date  path  organization  writes  references  article  \
0        2      1     1     1             1       1           1        0   
1        1      1     1     1             1       0           0        1   
2        1      1     1     1             1       1           1        1   
3        1      1     1     1             1       0           1        0   
4        1      1     1     1             0       0           0        0   

   sender  people       ...         modern  stay  countries  gm  heaven  \
0       0       0       ...              0     0          0   0       0   
1       0       1       ...              0     0          0   0       0   
2       1       2       ...              0     0          0   0       0   
3       0       0       ...              0     0          0   0       0   
4       0       0       ...              0     0          0   0       0   

   social  at&t  gateway  logic           _CLASS  
0       0     0        0      0  sci.electronics  
1       0     0        0      0  sci.electronics  
2       0     0        0      0  sci.electronics  
3       0     0        0      0  sci.electronics  
4       0     0        0      0  sci.electronics  

[5 rows x 1001 columns]

# train processing


In [6]:
train._CLASS = pd.Categorical(train._CLASS)
train["CLASS_CD"] = train._CLASS.cat.codes

In [7]:
del train["_CLASS"]

In [8]:
training_data = train.values

In [9]:
training_data

array([[ 1,  1,  1, ...,  0,  0, 12],
       [ 1,  1,  1, ...,  0,  0, 12],
       [ 1,  2,  1, ...,  0,  0, 12],
       ...,
       [ 1,  1,  1, ...,  0,  0,  3],
       [ 1,  1,  1, ...,  0,  0,  3],
       [ 1,  1,  1, ...,  0,  0,  3]])

In [10]:
#for 1000 words dataset
np.savetxt("preprocessed_x_y_train.csv", training_data, delimiter=",")

In [11]:
x_train = training_data[:,:-1]
y_train = training_data[:,-1]

In [12]:
x_train, y_train

(array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 2, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]]), array([12, 12, 12, ...,  3,  3,  3]))

 # testing processing

In [13]:
test._CLASS = pd.Categorical(test._CLASS)
test["CLASS_CD"] = test._CLASS.cat.codes

In [14]:
del test["_CLASS"]

In [15]:
testing_data = test.values

In [16]:
testing_data

array([[ 2,  1,  1, ...,  0,  0, 12],
       [ 1,  1,  1, ...,  0,  0, 12],
       [ 1,  1,  1, ...,  0,  0, 12],
       ...,
       [ 1,  1,  1, ...,  0,  0,  3],
       [ 1,  1,  1, ...,  0,  0,  3],
       [ 1,  1,  1, ...,  2,  0,  3]])

In [17]:
# #for 1000 words dataset
np.savetxt("preprocessed_x_y_test.csv", testing_data, delimiter=",")

In [18]:
x_test = testing_data[:,:-1]
y_test = testing_data[:,-1]

In [19]:
x_test, y_test

(array([[2, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 1, 0, 0],
        [1, 1, 1, ..., 0, 2, 0]]), array([12, 12, 12, ...,  3,  3,  3]))